[project]
name = "smart-intercom"
version = "0.1.0"
description = ""
authors = [
    {name = "e.kozlova",email = "kozlova03@inbox.ru"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "pydantic-core (>=2.37.2,<3.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "uvicorn (>=0.35.0,<0.36.0)",
    "fastapi (>=0.116.1,<0.117.0)",
    "sqlalchemy (>=2.0.42,<3.0.0)",
    "pytz (>=2025.2,<2026.0)",
    "fastapi-filter (>=2.0.1,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "torch (>=2.11.0,<3.0.0)",
    "redis (>=6.4.0,<7.0.0)",
    "aioboto3 (>=15.0.0,<16.0.0)",
    "pgvector (>=0.4.2,<0.5.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
