"""changed-visit-person

Revision ID: 1a6f7300739d
Revises: 88a7cb90b814
Create Date: 2026-05-15 19:21:17.030102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a6f7300739d'
down_revision: Union[str, None] = '88a7cb90b814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('first_name', sa.String(), nullable=False), schema='persons')
    op.add_column('person', sa.Column('last_name', sa.String(), nullable=False), schema='persons')
    op.add_column('person', sa.Column('middle_name', sa.String(), nullable=True), schema='persons')
    op.drop_column('person', 'full_name', schema='persons')
    op.add_column('visit', sa.Column('visitor_goal', sa.String(), nullable=True, comment='Purpose of the visit detected by bot'), schema='visits')
    op.alter_column('visit', 'photo_s3_path',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='S3 path to photo of the visit',
               schema='visits')
    op.drop_column('visit', 'purpose', schema='visits')
    op.drop_column('visit', 'finish_reason', schema='visits')
    op.add_column('visit_person', sa.Column('crop_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Visitor face coords on photo: y1, y2, x1, x2'), schema='visits')
    op.alter_column('visit_person', 'person_sid',
               existing_type=sa.UUID(),
               nullable=True,
               schema='visits')
    op.drop_column('visit_person', 'photo', schema='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_person', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False, comment='S3 path to photo of a person taken during a visit'), schema='visits')
    op.alter_column('visit_person', 'person_sid',
               existing_type=sa.UUID(),
               nullable=False,
               schema='visits')
    op.drop_column('visit_person', 'crop_coords', schema='visits')
    op.add_column('visit', sa.Column('finish_reason', sa.VARCHAR(), autoincrement=False, nullable=True, comment='The reason the visit was finished'), schema='visits')
    op.add_column('visit', sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Purpose of the visit detected by bot'), schema='visits')
    op.alter_column('visit', 'photo_s3_path',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='S3 path to photo of the visit',
               schema='visits')
    op.drop_column('visit', 'visitor_goal', schema='visits')
    op.add_column('person', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='persons')
    op.drop_column('person', 'middle_name', schema='persons')
    op.drop_column('person', 'last_name', schema='persons')
    op.drop_column('person', 'first_name', schema='persons')
    # ### end Alembic commands ###
