"""add indexes

Revision ID: 265edd722715
Revises: 8d6feb5313e1
Create Date: 2026-05-29 09:25:41.907328

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265edd722715'
down_revision: Union[str, None] = '8d6feb5313e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'face_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=False,
               schema='persons')
    op.create_index('idx_person_face_embedding', 'person', ['face_embedding'], unique=False, schema='persons', postgresql_using='hnsw', postgresql_ops={'face_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_visits_visit_granted_access'), 'visit', ['granted_access'], unique=False, schema='visits')
    op.create_index(op.f('ix_visits_visit_status'), 'visit', ['status'], unique=False, schema='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_status'), table_name='visit', schema='visits')
    op.drop_index(op.f('ix_visits_visit_granted_access'), table_name='visit', schema='visits')
    op.drop_index('idx_person_face_embedding', table_name='person', schema='persons', postgresql_using='hnsw', postgresql_ops={'face_embedding': 'vector_cosine_ops'})
    op.alter_column('person', 'face_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False,
               schema='persons')
    # ### end Alembic commands ###
