"""add-visit-call-employee-datetime

Revision ID: 6723b75d5c17
Revises: 265edd722715
Create Date: 2026-06-12 00:01:32.530272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6723b75d5c17'
down_revision: Union[str, None] = '265edd722715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('call_employee_datetime', sa.DateTime(), nullable=True), schema='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'call_employee_datetime', schema='visits')
    # ### end Alembic commands ###
