"""create-tables

Revision ID: 88a7cb90b814
Revises: 
Create Date: 2026-05-03 18:27:47.314165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '88a7cb90b814'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('photo_s3_path', sa.String(), nullable=False, comment='S3 path to person photo'),
    sa.Column('face_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('person_type', sa.Integer(), nullable=False, comment='Employee or Visitor'),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='persons',
    comment='persons module schema'
    )
    op.create_index(op.f('ix_persons_person_person_type'), 'person', ['person_type'], unique=False, schema='persons')
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='User role name'),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users',
    comment='users module schema'
    )
    op.create_table('user',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users.role.id'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('email'),
    schema='users',
    comment='users module schema'
    )
    op.create_table('visit',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('granted_access', sa.Boolean(), nullable=True, comment="User's decision to grant access"),
    sa.Column('bot_granted_access', sa.Boolean(), nullable=True, comment="Bot's recommendation to grant access"),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('finish_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True, comment='Purpose of the visit detected by bot'),
    sa.Column('finish_reason', sa.String(), nullable=True, comment='The reason the visit was finished'),
    sa.Column('dialogue_lang', sa.String(), nullable=False, comment='Visit dialogue language'),
    sa.Column('photo_s3_path', sa.String(), nullable=False, comment='S3 path to photo of the visit'),
    sa.Column('decision_by_user_sid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['decision_by_user_sid'], ['users.user.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    schema='visits',
    comment='visits module schema'
    )
    op.create_table('message',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('audio_s3_path', sa.String(), nullable=True, comment='S3 path to audio file'),
    sa.Column('visit_sid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['visit_sid'], ['visits.visit.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    schema='messages',
    comment='messages module schema'
    )
    op.create_table('visit_person',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('detected_sex', sa.Integer(), nullable=True),
    sa.Column('detected_age', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=False, comment='S3 path to photo of a person taken during a visit'),
    sa.Column('person_sid', sa.Uuid(), nullable=False),
    sa.Column('visit_sid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_sid'], ['persons.person.sid'], ),
    sa.ForeignKeyConstraint(['visit_sid'], ['visits.visit.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    schema='visits',
    comment='visits module schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_person', schema='visits')
    op.drop_table('message', schema='messages')
    op.drop_table('visit', schema='visits')
    op.drop_table('user', schema='users')
    op.drop_table('role', schema='users')
    op.drop_index(op.f('ix_persons_person_person_type'), table_name='person', schema='persons')
    op.drop_table('person', schema='persons')
    # ### end Alembic commands ###
