"""added-visit-additional-params

Revision ID: 8d6feb5313e1
Revises: 1a6f7300739d
Create Date: 2026-05-27 22:44:12.467002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6feb5313e1'
down_revision: Union[str, None] = '1a6f7300739d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('finish_reason', sa.Integer(), nullable=True, comment='Why visit was finished'), schema='visits')
    op.add_column('visit', sa.Column('handoff_reason', sa.Integer(), nullable=True, comment='Why employee was called'), schema='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'handoff_reason', schema='visits')
    op.drop_column('visit', 'finish_reason', schema='visits')
    # ### end Alembic commands ###
