x-env: &default-env
  env_file:
    - ../.env

services:
  postgres-smart-intercom:
    container_name: postgres-smart-intercom
    image: pgvector/pgvector:pg15
    <<: *default-env
    ports:
      - "5432:5432"
    volumes:
      - /docker-volumes/smart-intercom/postgres:/var/lib/postgresql/data
    networks:
      - smart-intercom-network

networks:
  smart-intercom-network:
    name: smart-intercom-network
